
meta_product_name: "Taff'On"
meta_title: "Taff'On - Trouve le bon téchnicien pour tes urgences de scéne!"
meta_description: "Taff'On offre aux organisateurs d'évenement la possibilité de trouver les bons techniciens de scenes, rapidement et efficacement."
meta_image: "cover.jpg" # should exist in `app/assets/images/`