
meta_product_name: "Taff'On"
meta_title: "Taff'On - Trouver le bon technicien pour une urgence du spectacle et de l'événementiel!"
meta_description: "Taff'On offre aux organisateurs d'évenements la possibilité de trouver les bons techniciens de scene, rapidement et efficacement."
meta_image: "cover.jpg" # should exist in `app/assets/images/`