
meta_product_name: "Taff'On"
meta_title: "Taff'On - Trouver le bon technicien pour tes urgences de scene!"
meta_description: "Taff'On offre aux organisateurs d'évenement la possibilité de trouver les bons techniciens de scenes, rapidement et efficacement."
meta_image: "banner.jpg" # should exist in `app/assets/images/`